Option to ignore uknown block types with overridable serializer
sanity-io/block-content-to-hyperscript pull request #13
Opened 2019-11-21 14:33 UTC by skogsmaskin

Option to ignore uknown block types with overridable serializer.

2019-11-21 17:49 UTC, rexxars requested changes
Typo throughout: should be `ignoreUnknownTypes`.

2019-11-21 17:57 UTC, skogsmaskin commented
Hah...at least it was consistent ;) Force pushed fix.

2019-11-21 19:11 UTC, rexxars approved these changes
👍

2019-12-03 15:15 UTC, kmelve commented
Could we inverse this, and rather add `errorUnknownTypes`? People keep stumbling on the current error behavior.

2019-12-03 16:20 UTC, rexxars approved these changes

2019-12-03 16:20 UTC, rexxars commented
I'm fine with changing the default to not throw.

2020-06-19 07:20 UTC, barbogast commented
@rexxars Would it be possible to get this PR merged? 🙏

2020-11-18 12:49 UTC, balazsorban44 commented
@rexxars Anything holding this back still? :)

2021-05-15 01:11 UTC, merged